FROM viciware/php
MAINTAINER Nik Petersen (Viciware LLC)

RUN mkdir -p /usr/local/ioncube/

COPY ioncube_loader_lin_5.6.so /usr/local/ioncube/ioncube_loader_lin_5.6.so
COPY ioncube_loader_lin_5.6_ts.so /usr/local/ioncube/ioncube_loader_lin_5.6_ts.so
COPY ioncube.ini /usr/local/etc/php/conf.d/

